import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <!-- Google Web Font --> */}
        <link href="http://fonts.googleapis.com/css?family=Raleway:300,500,900%7COpen+Sans:400,700,400italic" rel="stylesheet" type="text/css" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <script src="/assets/js/common.js"></script>
        <script type="text/javascript" src="/assets/js/common/jquery-1.11.1.min.js"></script>
        <script type="text/javascript" src="/assets/js/common/bootstrap.min.js"></script>
        <script type="text/javascript" src="/assets/js/common/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="/assets/js/common/chosen.min.js"></script>
        <script type="text/javascript" src="/assets/js/common/bootstrap-checkbox.js"></script>
        <script type="text/javascript" src="/assets/js/common/nice-scroll.js"></script>
        <script type="text/javascript" src="/assets/js/common/jquery-browser.js"></script>
        <script type="text/javascript" src="/assets/js/scripts.js"></script>
      </body>
    </html>
  );
}
